import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/navbar/Navbar";
import Footer from "@/_components/footer/Footer";
// import { Rubik } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body suppressHydrationWarning={true} className={rubik.className} style={{padding:'20px'}}></body> */}
      <body className={inter.className}>
        <div className="container">
          <Navbar></Navbar>
            {children}          
          <Footer></Footer>          
        </div>
      </body>
    </html>
  );
}
